web:
  hostname: 104.248.26.168
  user: debian
  port: 22
  deploy_path: /home/debian/demo-pipeline-laravel-deploy
  identityFile: ~/.ssh/id_rsa
  forwardAgent: true
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  stage: production
  roles:
    - webfront
