web:
  hostname: 68.183.208.144
  user: debian
  port: 22
  deploy_path: /home/debian/
  identityFile: ~/.ssh/id_rsa
  forwardAgent: true
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  stage: production
  roles:
    - webfront
